<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="tests.khly6517.Khly6517Tests-20210915154340" tests="7" file="tests/khly6517.py" time="21.150" timestamp="2021-09-15T15:44:15" failures="1" errors="0" skipped="0">
	<testcase classname="tests.khly6517.Khly6517Tests" name="test_WHEN_button_current_pressed_THEN_PVs_set" time="0.414" timestamp="2021-09-15T15:43:54" file="tests\khly6517.py" line="92"/>
	<testcase classname="tests.khly6517.Khly6517Tests" name="test_WHEN_button_pressed_THEN_queue_cleared" time="3.791" timestamp="2021-09-15T15:43:58" file="tests\khly6517.py" line="69"/>
	<testcase classname="tests.khly6517.Khly6517Tests" name="test_WHEN_buttons_pressed_THEN_readings_read_from_device" time="1.782" timestamp="2021-09-15T15:43:59" file="tests\khly6517.py" line="122"/>
	<testcase classname="tests.khly6517.Khly6517Tests" name="test_WHEN_errors_added_THEN_refresh_clears_queue_over_time" time="3.371" timestamp="2021-09-15T15:44:03" file="tests\khly6517.py" line="107"/>
	<testcase classname="tests.khly6517.Khly6517Tests" name="test_WHEN_set_pv_is_set_THEN_pv_updated_func" time="2.437" timestamp="2021-09-15T15:44:12" file="tests\khly6517.py" line="49"/>
	<testcase classname="tests.khly6517.Khly6517Tests" name="test_WHEN_set_pv_is_set_THEN_pv_updated_rang" time="2.695" timestamp="2021-09-15T15:44:15" file="tests\khly6517.py" line="53"/>
	<testcase classname="tests.khly6517.Khly6517Tests" name="test_WHEN_periodic_refresh_scanned_THEN_func_updated_and_errors_shown" time="6.660" timestamp="2021-09-15T15:44:09" file="tests\khly6517.py" line="57">
		<failure type="AssertionError" message="Expected PV, 'TE:NDW1798:KHLY6517_01:SYST:ERR' to have value '2' (type: 'int').
Final PV value was '0.0' (type: 'float')"><![CDATA[Traceback (most recent call last):
  File "C:\Instrument\Apps\EPICS\support\khly6517\master\system_tests\tests\khly6517.py", line 65, in test_WHEN_periodic_refresh_scanned_THEN_func_updated_and_errors_shown
    self.ca.assert_that_pv_is("SYST:ERR", 2)
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 269, in assert_that_pv_is
    return self.assert_that_pv_value_causes_func_to_return_true(
  File "C:\Instrument\Apps\EPICS\support\IocTestFramework\master\utils\channel_access.py", line 248, in assert_that_pv_value_causes_func_to_return_true
    raise AssertionError(err)
AssertionError: Expected PV, 'TE:NDW1798:KHLY6517_01:SYST:ERR' to have value '2' (type: 'int').
Final PV value was '0.0' (type: 'float')
]]></failure>
	</testcase>
</testsuite>
